language: csharp
mono: 3.8.0
solution: Aura.sln
branches:
  only:
    - master
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2a89565de8b44022eff4
    on_success: change
    on_failure: always
    on_start: never
before_install:
  - wget http://aura-project.org/xunit.runners.1.9.2.zip
  - unzip xunit.runners.1.9.2.zip
install:
  - nuget restore Aura.sln
  #- nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Aura.sln
  - mono --debug ./testrunner/xunit.runners.*/tools/xunit.console.clr4.exe ./src/Test.ChannelServer/bin/Release/Test.ChannelServer.dll
  - mono --debug ./testrunner/xunit.runners.*/tools/xunit.console.clr4.exe ./src/Test.Data/bin/Release/Test.Data.dll
  - mono --debug ./testrunner/xunit.runners.*/tools/xunit.console.clr4.exe ./src/Test.Mabi/bin/Release/Test.Mabi.dll
  - mono --debug ./testrunner/xunit.runners.*/tools/xunit.console.clr4.exe ./src/Test.Shared/bin/Release/Test.Shared.dll
